name: OpenWrt Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev gawk git gettext libssl-dev xsltproc zlib1g-dev

    - name: Clone OpenWrt source
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy custom .config
      run: |
        cp ../.config openwrt/.config

    - name: Build firmware
      run: |
        cd openwrt
        make defconfig
        make -j$(nproc)

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: openwrt/bin/targets/
